from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from reportlab.lib.units import inch
from datetime import datetime

def generate_credit_report(company_name, financial_data, news, analysis, output_path="credit_report.pdf"):
    
    doc = SimpleDocTemplate(
        output_path,
        pagesize=A4,
        rightMargin=50,
        leftMargin=50,
        topMargin=50,
        bottomMargin=50
    )
    
    styles = getSampleStyleSheet()
    story = []

    # ==============================
    # HEADER
    # ==============================
    header_style = ParagraphStyle(
        "Header",
        fontSize=28,
        textColor=colors.HexColor("#1a3c6e"),
        spaceAfter=8,
        spaceBefore=5,
        fontName="Helvetica-Bold",
        alignment=1,
        leading=34
    )
    
    subheader_style = ParagraphStyle(
        "SubHeader",
        fontSize=11,
        textColor=colors.HexColor("#888888"),
        spaceAfter=10,
        fontName="Helvetica",
        alignment=1,
        leading=16
    )

    # ✅ UPDATED: CredX branding - no emoji (ReportLab doesn't support emojis)
    story.append(Paragraph("CredX", header_style))
    story.append(Paragraph("The X Factor in AI-Powered Credit Intelligence", subheader_style))
    story.append(HRFlowable(width="100%", thickness=2, color=colors.HexColor("#1a3c6e")))
    story.append(Spacer(1, 15))

    # ==============================
    # REPORT DETAILS
    # ==============================
    section_style = ParagraphStyle(
        "Section",
        fontSize=13,
        textColor=colors.HexColor("#1a3c6e"),
        spaceAfter=8,
        fontName="Helvetica-Bold"
    )

    normal_style = ParagraphStyle(
        "Normal",
        fontSize=10,
        textColor=colors.HexColor("#333333"),
        spaceAfter=5,
        fontName="Helvetica",
        leading=16
    )

    date_str = datetime.now().strftime("%d %B %Y")
    story.append(Paragraph(f"<b>Company:</b> {company_name}", normal_style))
    story.append(Paragraph(f"<b>Report Date:</b> {date_str}", normal_style))
    story.append(Paragraph(f"<b>Report Type:</b> Comprehensive Credit Appraisal Memo (CAM)", normal_style))
    story.append(Paragraph(f"<b>Powered by:</b> CredX AI Engine", normal_style))
    story.append(Spacer(1, 15))

    # ==============================
    # FINANCIAL DATA
    # ==============================
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#cccccc")))
    story.append(Spacer(1, 10))
    story.append(Paragraph("1. FINANCIAL DATA EXTRACTED", section_style))

    for category, lines in financial_data.items():
        if lines:
            story.append(Paragraph(f"<b>{category.replace('_', ' ').title()}:</b>", normal_style))
            for line in lines:
                story.append(Paragraph(f"• {line}", normal_style))
    
    story.append(Spacer(1, 15))

    # ==============================
    # NEWS SECTION
    # ==============================
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#cccccc")))
    story.append(Spacer(1, 10))
    story.append(Paragraph("2. RECENT NEWS & MARKET INTELLIGENCE", section_style))
    
    for line in news.split("\n"):
        if line.strip():
            story.append(Paragraph(f"• {line.strip()}", normal_style))
    
    story.append(Spacer(1, 15))

    # ==============================
    # AI ANALYSIS
    # ==============================
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#cccccc")))
    story.append(Spacer(1, 10))
    story.append(Paragraph("3. AI CREDIT ANALYSIS & RECOMMENDATION", section_style))

    for line in analysis.split("\n"):
        if line.strip():
            if line.strip().startswith(("1.", "2.", "3.", "4.", "5.", "6.", "7.", "8.")):
                story.append(Paragraph(f"<b>{line.strip()}</b>", normal_style))
            else:
                story.append(Paragraph(line.strip(), normal_style))

    story.append(Spacer(1, 15))

    # ==============================
    # FOOTER
    # ==============================
    story.append(HRFlowable(width="100%", thickness=2, color=colors.HexColor("#1a3c6e")))
    story.append(Spacer(1, 10))
    
    footer_style = ParagraphStyle(
        "Footer",
        fontSize=8,
        textColor=colors.HexColor("#999999"),
        alignment=1
    )

    # ✅ UPDATED: CredX branding in footer
    story.append(Paragraph("This report is generated by CredX AI Engine. For official use only.", footer_style))
    story.append(Paragraph(f"Generated on {date_str} | CredX — The X Factor in AI-Powered Credit Intelligence", footer_style))

    doc.build(story)
    return output_path